# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=image.models.photo_path)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
