# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20160919_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pusblished',
            new_name='published',
        ),
    ]
