# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20160919_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', to='image.Photo'),
        ),
    ]
