# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_album_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
