# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_album_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='image.Photo'),
        ),
    ]
