# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField()),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('camera_type', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('is_professional', models.BooleanField()),
                ('hireable', models.BooleanField()),
                ('website', models.CharField(max_length=128)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
