# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hireable',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_professional',
        ),
    ]
