# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20160914_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hireable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
    ]
